---
title: "p8105_hw6_as6183"
output: github_document
---
# Problem 1
```{r}
library(tidyverse)

data = read.csv("./data/homicide-data.csv")%>%
  mutate(city_state = str_c(city,state,sep=", "),
         solved = ifelse(disposition != "Closed by arrest",0,1))%>%
  filter(city_state != "Dallas, TX" & city_state != "Phoenix, AZ" & city_state != "Kansas City, MO" & city_state != "Tulsa, AL")%>%
  filter(victim_race == "Black" | victim_race == "White")%>%
  mutate(victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White"))

glm_Bmore = data%>%
  filter(city_state == "Baltimore, MD")%>%
  glm(formula = solved~victim_age+victim_sex+victim_race,data = ., family=binomial)

glm_Bmore%>%
   broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  cbind(exp(confint(glm_Bmore)))%>%
  rename(conf.low = `2.5 %`,
         conf.high = `97.5 %`)%>%
  select(term, log_OR = estimate, OR, p.value,conf.low,conf.high)%>% 
  knitr::kable(digits = 3)

glm_all =
  data %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = map(data, ~ glm(formula = solved~victim_age+victim_sex+victim_race,data = .x, family=binomial)),
    results = map(models, broom::tidy)) %>%
  mutate(map_dfr(.x = models, .f = ~exp(confint(.x,'victim_raceBlack'))))%>% 
  select(-data,-models)%>%
  unnest(results)%>% 
  mutate(OR = exp(estimate)) %>%
  filter(term == "victim_raceBlack")%>%
  rename(conf.low = `2.5 %`,
         conf.high = `97.5 %`)%>%
  select(city_state,term,OR, p.value,conf.low,conf.high) 

glm_all%>%
   ggplot(aes(x = reorder(city_state,OR), y = OR)) +
   geom_bar(stat="identity", fill = "light blue", col = "white")+
   geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
   xlab("City")+
   ylab("Odds Ratio for solving Homicides comparing Black to White Victims")+
   ggtitle("Odds Ratio for Solving Homicides based on Victim's Race by City")+
   theme(
     axis.text.x = element_text
     (
       size=8,
       angle=90,
       vjust = 0.5, 
       hjust = 1
       ),
     axis.title.y = element_text(size=8),
     plot.title=element_text(size=11)
         )
```

# Problem 2: 

```{r}
data = read.csv("./data/birthweight.csv")%>%
  mutate(babysex = factor(babysex),
         frace = factor(frace),
         malform = factor(malform),
         mrace = factor(mrace),
         fincome = factor(fincome))
```

Proposed Regression Model:

```{r}
library(modelr)

proposed_model = lm(bwt~frace+malform+mrace+smoken,data = data)

proposed_model%>% 
  broom::tidy() %>% 
  select(term, estimate, p.value)%>%
  knitr::kable(digits=3)

data%>%
  modelr::add_residuals(proposed_model)%>%
  modelr::add_predictions(proposed_model)%>%
  ggplot(aes(pred,resid))+geom_point()
```

**Description of Modeling Process and Graph:**

```{r}
cv_df = 
  crossv_mc(data, 100)%>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(
    proposed_model  = map(train, ~lm(bwt~frace+malform+mrace+smoken,data = .x)),
    model_1  = map(train, ~lm(bwt~gaweeks+blength,data = .x)),
    model_2  = map(train, ~lm(bwt~bhead*blength+blength*babysex+bhead*babysex+bhead*babysex*blength,data = .x))) %>% 
  mutate(
    rmse_proposed = map2_dbl(proposed_model, test, ~rmse(model = .x, data = .y)),
    rmse_1 = map2_dbl(model_1, test, ~rmse(model = .x, data = .y)),
    rmse_2 = map2_dbl(model_2, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

# Problem 3:

```{r}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )

bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x) ),
    r2 = map(models,broom::glance),
    results = map(models, broom::tidy)) %>% 
  select(-strap_sample, -models) %>% 
  unnest(results)%>%
  select(-c(p.value,statistic,std.error))%>%
  unnest(r2)%>%
  select(strap_number,term,estimate,r.squared)%>%
  pivot_wider(names_from = term, values_from = estimate)%>%
  mutate(log = log(`(Intercept)`*tmin))

library(patchwork)

plot_1 = bootstrap_results%>%
   ggplot(aes(x = r.squared)) + 
  geom_density()+
  xlab("r.squared")+
  ylab("density")+
  xlim(c(0.87,0.96))+
  ggtitle("Distribution of R squared values")

plot_2 = bootstrap_results%>%
  ggplot(aes(x = log)) + 
  geom_density()+
  xlab("log(B0*B1)")+
  ylab("density")+
  ggtitle("Distribution of log(B0*B1) values")

plot_1 + plot_2
```

**Explanation of R squared and log(B0B1) Results:**


**Calculating Confidence Intervals:**

```{r}
confidence_r2 = bootstrap_results%>%
  summarize(
    ci_lower = quantile(r.squared,0.025), 
    ci_upper = quantile(r.squared,0.975))

confidence_log = bootstrap_results%>%
  summarize(
    ci_lower = quantile(log,0.025), 
    ci_upper = quantile(log,0.975))

confidence_r2%>%
  knitr::kable(caption = "95% Confidence Interval for R Squared", format = "html", digits = 3)

confidence_log%>%
  knitr::kable(caption = "95% Confidence Interval for log(B0*B1)", format = 'html', digits = 3)
```